### ISSUE TITLE
Can't run scheduler

### ISSUE THREAD

**Issue by aungkokolin-safecoms** [hydrosIII/odoo12-stock-correction#1]
Thread <Thread(odoo.service.http.request.140075917297408, started 140075917297408)> virtual real time limit (173/120s) reached

**Comment by hydrosIII** [comment]
Depending on the power of your machine an database server. It can take all nigth. So:

1. Run it at night when nobody is using the server. 
2. Modify odoo.conf to increase the virtual real time limit, and the time limit in general. It can take several hours.

**Comment by hydrosIII** [comment]
That is why the repository https://github.com/hydrosIII/odoo12-stock-correct-short is for, after a succesful run, you can run just an update.

**Comment by hydrosIII** [comment]
Here is an example of my odoo.conf:

`````
limit_request = 819200
limit_time_cpu = 60000
limit_time_real = 60000


``````
